### ISSUE TITLE
Only Display Snippets when the string starts with _.

### ISSUE THREAD

**Issue by mrhammadasif** [tomphilbin/lodash-snippets#112]
The snippets Quick Suggestions will only show, or match when we type in **_.**

**Comment by mrhammadasif** [comment]
Similar to https://github.com/OYsun/Vscode-Lodash-Snippents

**Comment by tomphilbin** [comment]
Hi,

I don't personally think that this would be right for these snippets. The advantage of not having the "\_." at the beginning is that it is quicker to type, so if I want to use "\_.map" I type "map", hit tab and the "\_." gets prepended for me. Two less keyboard taps and more time for beer and pizza 👍 

If you prefer OYsun's snippets for having the "\_." at the beginning then I won't be offended if you use it 😃 

Cheers!

Tom

**Comment by Jule-** [comment]
The drawback of your approach @tomphilbin is that it pollutes the completion for all native functions like Array.map for example. For people who try to use as less as possible external dependencies and thus try to use lodash only when it is really necessary (cf. https://youmightnotneed.com/lodash/) it is a no go for using your extension.

As a developper I want my completion to give me what I am looking for thus when I want lodash function a natural reflex is to type `_` and then the method I want to call (only 1 meaningful keypress IMHO).
Ex: `_m => _.map()` like OYsun does. The only issue with the other extension is the disturbing Chinese characters.

An option would be nice. 😃What do you think?

**Comment by tomphilbin** [comment]
@Jule- I’ll be happy to publish the change if you’d like to open a pull request for this.
